#pragma once
#define EXPORT_VAR extern
#define EXPORT_FUNC
// Standard C++ includes
#include <algorithm>
#include <chrono>
#include <iostream>
#include <random>

// Standard C includes
#include <cassert>
#include <cmath>
#include <cstdint>
#include <cstring>
#define DT 1.00000000000000000e+00f
typedef float scalar;
#define SCALAR_MIN 1.175494351e-38f
#define SCALAR_MAX 3.402823466e+38f

#define TIME_MIN 1.175494351e-38f
#define TIME_MAX 3.402823466e+38f

// ------------------------------------------------------------------------
// bit tool macros
#define B(x,i) ((x) & (0x80000000 >> (i))) //!< Extract the bit at the specified position i from x
#define setB(x,i) x= ((x) | (0x80000000 >> (i))) //!< Set the bit at the specified position i in x to 1
#define delB(x,i) x= ((x) & (~(0x80000000 >> (i)))) //!< Set the bit at the specified position i in x to 0

extern "C" {
// ------------------------------------------------------------------------
// global variables
// ------------------------------------------------------------------------
EXPORT_VAR unsigned long long iT;
EXPORT_VAR float t;

// ------------------------------------------------------------------------
// timers
// ------------------------------------------------------------------------
EXPORT_VAR double neuronUpdateTime;
EXPORT_VAR double initTime;
EXPORT_VAR double presynapticUpdateTime;
EXPORT_VAR double postsynapticUpdateTime;
EXPORT_VAR double synapseDynamicsTime;
EXPORT_VAR double initSparseTime;
// ------------------------------------------------------------------------
// local neuron groups
// ------------------------------------------------------------------------
#define spikeCount_Applied Current glbSpkCntApplied Current[0]
#define spike_Applied Current glbSpkApplied Current
#define glbSpkShiftApplied Current 0

EXPORT_VAR unsigned int* glbSpkCntApplied Current;
EXPORT_VAR unsigned int* glbSpkApplied Current;
EXPORT_VAR scalar* ValApplied Current;

// ------------------------------------------------------------------------
// postsynaptic variables
// ------------------------------------------------------------------------

// ------------------------------------------------------------------------
// synapse connectivity
// ------------------------------------------------------------------------

// ------------------------------------------------------------------------
// synapse variables
// ------------------------------------------------------------------------

EXPORT_FUNC void pushApplied CurrentSpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullApplied CurrentSpikesFromDevice();
EXPORT_FUNC void pushApplied CurrentCurrentSpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullApplied CurrentCurrentSpikesFromDevice();
EXPORT_FUNC unsigned int* getApplied CurrentCurrentSpikes();
EXPORT_FUNC unsigned int& getApplied CurrentCurrentSpikeCount();
EXPORT_FUNC void pushValApplied CurrentToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullValApplied CurrentFromDevice();
EXPORT_FUNC void pushCurrentValApplied CurrentToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentValApplied CurrentFromDevice();
EXPORT_FUNC scalar* getCurrentValApplied Current();
EXPORT_FUNC void pushApplied CurrentStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullApplied CurrentStateFromDevice();
// Runner functions
EXPORT_FUNC void copyStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void copyConnectivityToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void copyStateFromDevice();
EXPORT_FUNC void copyCurrentSpikesFromDevice();
EXPORT_FUNC void copyCurrentSpikeEventsFromDevice();
EXPORT_FUNC void allocateMem();
EXPORT_FUNC void freeMem();
EXPORT_FUNC size_t getFreeDeviceMemBytes();
EXPORT_FUNC void stepTime();

// Functions generated by backend
EXPORT_FUNC void updateNeurons(float t);
EXPORT_FUNC void updateSynapses(float t);
EXPORT_FUNC void initialize();
EXPORT_FUNC void initializeSparse();
}  // extern "C"
